### ISSUE TITLE
double legend is plotted

### ISSUE THREAD

**Issue by oflorez** [jacob-long/interactions#13]
Hi team,
When using interact_plot double legend is plotted when using modx and legend.main
`interact_plot(lm(log.10.analyte ~ numeric.variable1 * numeric.variable2, data = total_DB_plot),
              pred = numeric.variable1, 
              modx = numeric.variable2,
              plot.points = TRUE, jitter = 0.125, #  point.shape = TRUE
              x.label = "Name for variable 1",
              y.label = "Hg (\u03BCg Hg/L), log10",
              legend.main = "Name for variable 2",
              interval = TRUE, int.width = 0.8,
              color.class = "Blues",
              point.size = 2,
              point.shape = 19,
              facet.modx =  FALSE,
              modx.labels = NULL,
              modx.values = NULL)`

**Comment by jacob-long** [comment]
I'm not having any luck replicating this. Just to double check that I haven't already fixed it by accident, could you download the development version of `interactions` 

```r
devtools::install_github("jacob-long/interactions")
```

and let me know if you're still having the problem?

**Comment by oflorez** [comment]
Hi Jacob,
I didn't have luck with this. Now I am getting the following error:
Error: lazy-load database 'C:/Users/Documents/R/R-3.5.1/library/interactions/R/interactions.rdb' is corrupt
In addition: Warning messages:
1: restarting interrupted promise evaluation 
2: internal error -3 in R_decompress1

**Comment by jacob-long** [comment]
I think that's an error that is usually solved by restarting R.
