### ISSUE TITLE
limit the range of the y-axis in the interaction plot

### ISSUE THREAD

**Issue by mrmvergeer** [jacob-long/interactions#16]
Kudos for your packages :-)
Is it possible to limit the range of the y-axis in the interaction plot using interact_plot? If not would it be possible to include that as an option? Or is there a workaround?

best
Maurice

**Comment by jacob-long** [comment]
Yes it is! `interact_plot()` returns a `ggplot` object, which means you can use the tools in the `ggplot2` package to make changes like this. As an example,

```r
library(interactions) 
library(ggplot2)
states <- as.data.frame(state.x77)
states$HSGrad <- states$`HS Grad`
fit <- lm(Income ~ HSGrad + Murder * Illiteracy, data = states)
interact_plot(model = fit, pred = Murder, modx = Illiteracy) + ylim(4000, 5000)
```

The `+ ylim(4000, 5000)` in that code above restricts the y axis to the values between 4000 and 5000. You may see a warning about removing rows which is nothing to worry about.
