### ISSUE TITLE
sim_slopes error (non-numeric argument to binary operator)

### ISSUE THREAD

**Issue by baverwarug** [jacob-long/interactions#20]
Hi Jacob

Love using your package(s)! 
I just updated the 'interaction' package (via CRAN on 9th of May) and was re-running some old analyses. They now give me the following error, when trying to calculate simple slopes of an interaction in a merMod class model. Also tried it with some random test data and get the same results.
Code I used:
mod_model <- lmer(DV~IV*mod + (1|group), data=dat)
sim_slopes(mod_model, pred=IV, modx = mod)
Output:
Error in y3^2 : non-numeric argument to binary operator

Thanks for looking into it!

**Comment by jacob-long** [comment]
Interesting! I've had the same issue and thought maybe it was a random problem on my end. Thanks for reporting. I wonder if this may be caused by a change in `lme4`. I'm investigating...

**Comment by jacob-long** [comment]
Okay, I figured this out (and it was my fault, of course). If you want to get it working right away, you can download the development version via

```r
# assuming you have devtools package installed
devtools::install_github("jacob-long/interactions")
```

**Comment by baverwarug** [comment]
Great! Thanks a lot!
