### ISSUE TITLE
Problems with plot.sim_slopes

### ISSUE THREAD

**Issue by ngreifer** [jacob-long/interactions#22]
I'm having a problem with `plot.sim_slopes`. The plot has a few issues. First, the x-axis scale is kind of wild and it's not clear how to fix that (maybe through a digits argument?). Second, it's unclear why my confidence intervals are not symmetric around the point estimate, even though they are in the `sim_slopes` output. Below is an example using data from `cobalt`.

``` r
library("interactions")
data("lalonde", package = "cobalt")

fit <- lm(re78 ~ treat * race, data = lalonde)
plot(sim_slopes(fit, pred = "treat", modx = "race"))
#> Warning: Johnson-Neyman intervals are not available for factor moderators.
```

![](https://i.imgur.com/22OIUMU.png)

<sup>Created on 2019-05-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jacob-long** [comment]
I am...very surprised at how this error played out. Basically, this plot method relies on `broom::tidy()` via `jtools::plot_coefs()`. The `tidy()` method for `sim_slopes` objects was returning strings in the `estimate`, `ci.lower`, and `ci.upper` columns which led to...that.
