### ISSUE TITLE
Issue with cat_plot pred.values 

### ISSUE THREAD

**Issue by haylee-m** [jacob-long/interactions#23]
Hi, there seems to be an issue with the pred.values option of cat_plot. 

Firstly, although the factor I'm using is not ordered alphabetically, it is displaying so in the resulting interaction graph. I tried to resolve this using the pred.values option, yet this did not work. I also tried to select only certain values of pred, yet it still returns all of them. Wondering if it was just me, I switched the modx and pred variables, and tested it with modx.values option, which worked both to reorder the categories appearance, and to select only specific categories to show. Additionally, the modx.values option recognizes the factor order, rather than presenting it in alphabetical order. I also found in perhaps some older documentation, a predvals option, which I tried and also did not work. Neither are returning an error, it just seems that the option is not working as it should. 

I wonder if you could look into this? 

Many thanks!

**Comment by jacob-long** [comment]
I think I fixed this in the development version of the package when someone else reached out about a similar problem.

Run 

```r
devtools::install_github("jacob-long/interactions")
```

And I think it should be working.
