### ISSUE TITLE
error in sim_slopes/probe_interaction

### ISSUE THREAD

**Issue by philippahuepen** [jacob-long/interactions#24]
Dear Jacob,

I am getting an error message using probe_interaction (with the newest interactions version 1.1.0).
The model was estimated with lme4:
mixed.RT = lmer(RT ~ cont*factor1*factor2 + factor1*factor3 + (cont|Code), REML = TRUE, data=mydata)

probe_interaction(mixed.RT, pred = cont, modx = factor1, mod2 = factor2, alpha = .05)

 Error: One of the requested columns does not exist.
 Backtrace:
  1. interactions::probe_interaction(...)
  3. interactions::sim_slopes(...)
  7. jtools:::summ.merMod(...)
  8. jtools:::create_table(...)

I do not encouter any problems with the same data/code using an old jtools version

Thank you for your time!

**Comment by jacob-long** [comment]
Hi, I believe I just fixed this in the development version of the package.

Run 

```r
devtools::install_github("jacob-long/interactions")
```

And I think it should be working.

**Comment by mychan24** [comment]
Just want to add a note that updating with Github version works, but since it is replacing a version that has the same version #, add force=TRUE. 
```r 
devtools::install_github("jacob-long/interactions", force=TRUE)
```

**Comment by jrk1** [comment]
Unfortunately, I have the same issue, also with the newest version.
