### ISSUE TITLE
point.alpha not working

### ISSUE THREAD

**Issue by jasongullifer** [jacob-long/interactions#25]
Hi there,

I've been plotting interactions with data plots showing (plot.points=T). Sometimes I have many overlapping points, and I would like to lower the alpha level of the points with the point.alpha argument. However, the argument doesn't seem to change the plots in any way. 

E.g., Unless I'm misunderstanding something, the following code should produce completely transparent points, but I receive the following plot. 

```
library(interactions)
states <- as.data.frame(state.x77)
states$HSGrad <- states$\`HS Grad\`
fit <- lm(Income ~ HSGrad + Murder * Illiteracy, data = states)
interact_plot(model = fit, pred = Murder, modx = Illiteracy,, plot.points = T, point.alpha = .0001)
```
<img width="820" alt="Screen Shot 2019-08-14 at 14 36 15" src="https://user-images.githubusercontent.com/1056959/63046647-e9ea4500-bea0-11e9-864d-a6be901f5db9.png">

Thanks!

**Comment by jacob-long** [comment]
Thanks for reporting! This will be fixed in the next release.
