### ISSUE TITLE
Interaction plot resolution

### ISSUE THREAD

**Issue by quindi13** [jacob-long/interactions#27]
Trying to increase resolution of interaction simple slope plots but can't seem to get anything different than 96 dpi when using probe_interaction.

Any ideas?

**Comment by jacob-long** [comment]
That's not something that I think is under my control (and might vary based on operating system, etc.). 

If you're trying to save to file, the [`ggsave()`](https://ggplot2.tidyverse.org/reference/ggsave.html) function from `ggplot2` is a relatively straightforward method that includes an argument for DPI.
