### ISSUE TITLE
cat_plot Error in zero_range(from) : x must be length 1 or 2

### ISSUE THREAD

**Issue by annakau** [jacob-long/interactions#28]
I keep getting this error which is maybe coming from gglplot/scales and don't know how to fix it. 

My argument call format is
cat_plot(mdl, pred=factor1, modx=factor2, data=mdl.df)

My R version is 3.5.3, interactions 1.1.1, and ggplot2 3.2.1

I don't know if this is something you can fix here but just wanted to let you know.

**Comment by jacob-long** [comment]
The results of `traceback()` right after you have the error would help me with figuring out what might be happening.

**Comment by annakau** [comment]
Sorry about not responding. I still have this issue. traceback() gives

18: stop("x must be length 1 or 2")
17: zero_range(from)
16: rescale.numeric(major, from = range)
15: rescale(major, from = range)
14: f(..., self = self)
13: scale$break_info(range)
12: train_cartesian(scale_x, self$limits$x, "x")
11: f(..., self = self)
10: self$coord$setup_panel_params(scale_x, scale_y, params = self$coord_params)
9: (function (scale_x, scale_y) 
   {
       self$coord$setup_panel_params(scale_x, scale_y, params = self$coord_params)
   })(dots[[1L]][[1L]], dots[[2L]][[1L]])
8: mapply(FUN = f, ..., SIMPLIFY = FALSE)
7: Map(setup_panel_params, scales_x, scales_y)
6: f(..., self = self)
5: layout$setup_panel_params()
4: ggplot_build.ggplot(x)
3: ggplot_build(x)
2: print.ggplot(x)
1: function (x, ...) 
   UseMethod("print")(x)

**Comment by annakau** [comment]
Removing data-argument fixed the issue (the data I provided was the same used in modelling, though)
