### ISSUE TITLE
R: modx.labels() in interactions::sim_slopes()

### ISSUE THREAD

**Issue by davefest** [jacob-long/interactions#32]
Hello,

I am working with <code>sim_slopes()</code> in the R package <code>interactions</code>.  Running the code below, the requested labels "min", "mean", and "max" do not appear in the output.  Am I doing something wrong?

Thanks in advance for any suggestions.

Dave

<pre><code>  dat=data.frame(state.x77)
  reg.mod = lm(data=dat, Murder ~ Illiteracy * HS.Grad)
  sim_slopes(reg.mod, pred = Illiteracy, modx = HS.Grad,
    modx.values = c(min(dat$HS.Grad), mean(dat$HS.Grad),
    max(dat$HS.Grad)), modx.labels = c('Min', 
    'Mean', 'Max'))

JOHNSON-NEYMAN INTERVAL 

When HS.Grad is INSIDE the interval [-17.49, 63.42], the slope of Illiteracy is p < 
.05.

Note: The range of observed values of HS.Grad is [37.80, 67.30]

SIMPLE SLOPES ANALYSIS 

Slope of Illiteracy when HS.Grad = 37.80: 

  Est.   S.E.   t val.      p
------ ------ -------- ------
  5.65   1.43     3.95   0.00

Slope of Illiteracy when HS.Grad = 53.11: 

  Est.   S.E.   t val.      p
------ ------ -------- ------
  3.87   0.84     4.61   0.00

Slope of Illiteracy when HS.Grad = 67.30: 

  Est.   S.E.   t val.      p
------ ------ -------- ------
  2.22   1.60     1.39   0.17</code></pre>

**Comment by jacob-long** [comment]
Thanks for reporting! You found a bug.

**Comment by davefest** [comment]
Ok, thanks Jacob.

Dave


______________________

David Corey, Ph.D.

Department of Psychology

Tulane University

________________________________
