### ISSUE TITLE
Remove interaction legend

### ISSUE THREAD

**Issue by daisyburr** [jacob-long/interactions#40]
**Is your feature request related to a problem? Please describe.**
 I don't see a way to remove the legend (the moderating variable) in an interact_plot.

**Describe the solution you'd like**

is it possible to have an argument to entirely remove the legend in interact_plots?

**Describe any alternatives or other implementations that you might know of**

**Additional context**

**Comment by jacob-long** [comment]
In fact, all you need to do is:

```r 
library(ggplot2)
interact_plot(model, predictor, moderator) +
	theme(legend.position = "none")
```

This is using the theme options available in `ggplot2`'s `theme()` function.

**Comment by linem7** [comment]
Hello Jacob, I have a question about changing the legend of geom_segment(). Specifically, I want to change the legend text from "Range of observed data" to something else. I used the code below, but it didn't work. Do you know other easy way to do so? I would really appreciate any ideas or suggestions you have. Thank you!

```
object <- johnson_neyman(model = fit, pred = Murder,
               modx = Illiteracy)

object$plot + geom_segment(aes(x = 0.5, xend = 2.8, y = 10, yend = 10,
linetype = "range of moderate variable"),
lineend = "square", size = 1.25)
```
