### ISSUE TITLE
sim_slopes(): Error with ordered factors

### ISSUE THREAD

**Issue by jzadra** [jacob-long/interactions#42]
I have a model with an interaction between a continuous predictor and an ordered factor predictor.  

The sim_slopes() function gives the following error:
`Error in relevel.ordered(dt[[modx]], ref = as.character(modxvals2[i])) : 
  'relevel' only for unordered factors`

I was able to make it work by changing the lines of your code where you handle non-numeric modx/mod2 by adding `ordered = F` to the factor line. 

Original:
```
else {
        dt[[modx]] <- factor(dt[[modx]])
        dt[[modx]] <- relevel(dt[[modx]], ref = as.character(modxvals2[i]))
        dt[[modx]] <- stats::C(dt[[modx]], "contr.treatment")
      }
```

Fix:
```
else {
        dt[[modx]] <- factor(dt[[modx]], ordered = F)
        dt[[modx]] <- relevel(dt[[modx]], ref = as.character(modxvals2[i]))
        dt[[modx]] <- stats::C(dt[[modx]], "contr.treatment")
      }
```

And same for mod2.  

I would be curious to see if you think this will cause bad results, and if not perhaps it can be implemented?  I'm guessing that the ordering doesn't matter for simple slopes.

**Comment by alapo** [comment]
I just ran into the same problem.  Here is a reprex using `iris`

```r
pacman::p_load(tidyverse, interactions)


myData <- iris %>% 
           mutate(Species = factor(Species, ordered = TRUE, levels = c("setosa", "versicolor", "virginica")))
               
mod <- lm(Sepal.Length ~ Petal.Width*Species, data = myData)
interactions::sim_slopes(mod, pred = Petal.Width, modx = Species, jnplot = TRUE)

```

You are a more skilled coder than I am...I was not able to follow the 2nd and 3rd lines but running

```r
myData$Species <- factor(myData$Species, ordered=F)
```

This was the temporary fix I was seeking. But will still cause an error

```r
Warning message:
Johnson-Neyman intervals are not available for factor moderators. 
```

**Comment by jzadra** [comment]
The reason I didn't use your fix is that I needed the factor to be ordered in the model.  If the order doesn't matter, your fix works fine.

ALso, setting the argument `johnson_neyman = F` in the sim_slopes() function will remove the error.

**Comment by jacob-long** [comment]
Thank you for reporting this!
