### ISSUE TITLE
categorical predictor by continous moderator

### ISSUE THREAD

**Issue by marco-marinucci** [jacob-long/interactions#54]
Hi, I noticed something that I think it is a bug in the new version of the package "interactions". 
In the previous "jtools" package I used the function cat_plot to plot interaction between a categorical predictor and a continuous moderator. It worked well and I could specify a continuous variable as moderator. Now, in the "interactions" package's cat_plot this is not allowed anymore and it returns an error: the cat_plot function only admits categorical predictor and moderators. When trying to specify a continuous moderator in the cat_plot function I got the error: "Continuous value supplied to discrete scale". Further, I cannot specify a categorical predictor using the interact_plot function, which only admits continuous a predictor. Therefore, to me it seems that there is no way to plot a categorical*continuous interaction in the new "interactions" package.
Does any of you confirm this? do you have any suggestion on how to address it?

Thank you, 
best
Marco

**Comment by bgupsych** [comment]
Hey buddy. try to use probe_interaction instead

> Hi, I noticed something that I think it is a bug in the new version of the package "interactions". In the previous "jtools" package I used the function cat_plot to plot interaction between a categorical predictor and a continuous moderator. It worked well and I could specify a continuous variable as moderator. Now, in the "interactions" package's cat_plot this is not allowed anymore and it returns an error: the cat_plot function only admits categorical predictor and moderators. When trying to specify a continuous moderator in the cat_plot function I got the error: "Continuous value supplied to discrete scale". Further, I cannot specify a categorical predictor using the interact_plot function, which only admits continuous a predictor. Therefore, to me it seems that there is no way to plot a categorical*continuous interaction in the new "interactions" package. Does any of you confirm this? do you have any suggestion on how to address it?
> 
> Thank you, best Marco

Hey buddy. try to use probe_interaction instead

**Comment by jacob-long** [comment]
This feature has been added in 95234e638ac98361b624e1312cb9fb6bb2b24f9b. Use 

```r
devtools::install_github("jacob-long/interactions")
```

If you'd like the new version right away.
