### ISSUE TITLE
cannot change axis labels in sim_slopes 

### ISSUE THREAD

**Issue by mengliuveronica** [jacob-long/interactions#56]
Hi, I was trying to have sim_slopes display correct labels at the request of a reviewer. I cannot seem to find a way to make it work. 

My complete label contains more than one word so I changed the variable names before I ran the model and hope to pass them on to sim_slopes() so that I don't need to change labels from this function. When I specify the variable names with escape symbol, "`the variable name`", an error message is returned: 
"Error in `[.data.frame`(model.frame(model), , modx) : 
  undefined columns selected"

I wonder how to fix that? this is required before I could submit my revision. any input is appreciated. thank you!

**Comment by jacob-long** [comment]
Terribly sorry for the long delay, my new job robbed me of a lot of my time to stay up to date with issues here. I've corrected the bug you encountered and added options that should make it easier for people to avoid the need to change their variables' names just to get the axis labels looking the way they want.

**Comment by esellars1** [comment]
Hi there,

Thank you for such a helpful package. I am having a similar issue to the question above, when I try to relabel the x axis using modx.label, I get the following error message: Warning: modx.labels or mod2.labels argument is not the same length as the number of moderator values used. It will be ignored. I would prefer not to have to change the variable name in my dataset, so wondered if you would be able to help me with where I am going wrong!
