### ISSUE TITLE
sim_slopes error

### ISSUE THREAD

**Issue by HUtangge** [jacob-long/interactions#63]
When I run the sim_slopes(fiti, pred = hp, modx = wt), I came with the error message:
Error:
! `class` must be a character vector, not a list.
Backtrace:
 1. interactions::sim_slopes(fiti, pred = hp, modx = wt, jnplot = TRUE)
 3. jtools:::summ.lm(...)
 4. jtools:::do_robust(model, robust, cluster, data, vcov)
 5. jtools::get_robust_se(...)
 6. jtools::stop_wrap(...)
 8. rlang (local) `<fn>`(class = <named list>)

How could I resolve this issue, many thanks :)

**Comment by jacob-long** [comment]
This seems identical to jacob-long/jtools#132, so I'm going to close this here.
