### ISSUE TITLE
Corrigendum

### ISSUE THREAD

**Issue by vincentarelbundock** [jacob-long/interactions#66]
I have not invested enough time in this to know if it's a problem for you, but I just wanted to note that Esarey & Sumner published a corrigendum to their article. Feel free to close if you know this already or if it doesn't apply to the functions implemented in this package:

> the subsection of Esarey and Sumner (2018) titled “Underconfidence cor-
> rections for estimated marginal effects” and related material in the subsection titled “Specify
> theories with multiple predictions in advance and use bootstrapped critical-t statistics to
> maximize empirical power” is incorrect. In particular, the bootstrapped critical-t statistics
> reported in Table 5 of Esarey and Sumner (2018) should not be used. Those statistics corre-
> spond (for non-zero predictions) to t-values that occur 5% of the time or less in the situation
> where all marginal effects are equal to zero, the point null hypothesis discussed above. Ta-
> ble 5 in this paper confirms that the procedure works, but for the point null hypothesis
> for which all marginal effects are simultaneously equal to zero. This is not the appropriate
> null hypothesis space, as discussed above. We have removed the corresponding function for
> calculating these t-statistics from our R package

https://www.justinesarey.com/interaction-overconfidence-corrigendum.pdf

**Comment by jacob-long** [comment]
Thanks for making me aware of this, it looks like this doesn't concern the stuff I'm using from that paper.
